//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stip.BattleGames.Common; 
using System;


/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class UIStrings {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal UIStrings() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stip.BattleGames.Common.UIStrings", typeof(UIStrings).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Kan gegevens niet laden..
    /// </summary>
    public static string Error_CannotLoadData {
        get {
            return ResourceManager.GetString("Error_CannotLoadData", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Kan gegevens niet opslaan..
    /// </summary>
    public static string Error_CannotSaveData {
        get {
            return ResourceManager.GetString("Error_CannotSaveData", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Sluiten.
    /// </summary>
    public static string Global_Close {
        get {
            return ResourceManager.GetString("Global_Close", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Fout.
    /// </summary>
    public static string Global_Error {
        get {
            return ResourceManager.GetString("Global_Error", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Nee.
    /// </summary>
    public static string Global_No {
        get {
            return ResourceManager.GetString("Global_No", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Ja.
    /// </summary>
    public static string Global_Yes {
        get {
            return ResourceManager.GetString("Global_Yes", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Ben je zeker?.
    /// </summary>
    public static string Input_AreYouSure {
        get {
            return ResourceManager.GetString("Input_AreYouSure", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Ben je zeker dat je de applicatie wilt sluiten?.
    /// </summary>
    public static string Input_AreYouSureYouWantToClose {
        get {
            return ResourceManager.GetString("Input_AreYouSureYouWantToClose", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Ben je zeker dat je wilt resetten?.
    /// </summary>
    public static string Input_AreYouSureYouWantToReset {
        get {
            return ResourceManager.GetString("Input_AreYouSureYouWantToReset", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Ben je zeker dat je wilt stoppen?.
    /// </summary>
    public static string Input_AreYouSureYouWantToStop {
        get {
            return ResourceManager.GetString("Input_AreYouSureYouWantToStop", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to -1.
    /// </summary>
    public static string Input_Decrement {
        get {
            return ResourceManager.GetString("Input_Decrement", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to +1.
    /// </summary>
    public static string Input_Increment {
        get {
            return ResourceManager.GetString("Input_Increment", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Reset.
    /// </summary>
    public static string Input_Reset {
        get {
            return ResourceManager.GetString("Input_Reset", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Start.
    /// </summary>
    public static string Input_Start {
        get {
            return ResourceManager.GetString("Input_Start", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Stop.
    /// </summary>
    public static string Input_Stop {
        get {
            return ResourceManager.GetString("Input_Stop", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Grafiekvenster (de)maximaliseren.
    /// </summary>
    public static string Input_ToggleChartWindowState {
        get {
            return ResourceManager.GetString("Input_ToggleChartWindowState", resourceCulture);
        }
    }
}
